### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by ahmadie** [jake-stewart/swayfader#1]
when I try to run with : python3 swayfader.py the following error show

```
  File "swayfader.py", line 196
    if (c_id := e.container.id) not in self.floating_windows:
             ^
SyntaxError: invalid syntax
```
I replace it with following and it compile fine, but I am not sure about the logic ....
` if (c_id == e.container.id) not in self.floating_windows:`

I found another topic here about if( something := something) and it seems bleed-edge feature, can you please refactor this code to run on older python3, I am using debian buster with python official packages.
https://stackoverflow.com/questions/26000198/what-does-colon-equal-in-python-mean

**Comment by dnfm** [comment]
Yea, that's a feature that is not yet released in Python.  The correct fix for that I believe is:
```
diff --git a/swayfader.py b/swayfader.py
index 3e2febc..d867a67 100644
--- a/swayfader.py
+++ b/swayfader.py
@@ -193,7 +193,8 @@ class Fader:
         self.active_win = e.container
 
     def on_window_floating(self, ipc, e):
-        if (c_id := e.container.id) not in self.floating_windows:
+        c_id = e.container_id
+        if c_id not in self.floating_windows:
             self.floating_windows.append(c_id)
 
             if self.active_win.id != e.container.id:

```

**Comment by jake-is-a-legend** [comment]
yeah bro ill fix it or whatever
